### ISSUE TITLE
crash when losing

### ISSUE THREAD

**Issue by cburgard** [lettis/Kubix#43]
[xcb] Unknown request in queue while dequeuing
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
Kubix: Fatal IO error: client killed
Kubix: xcb_io.c:179: dequeue_pending_request: Assertion `!xcb_xlib_unknown_req_in_deq' failed.
zsh: abort (core dumped)  ./Kubix

{"mode":0,"next":-1,"aiDepth":2,"aiStrategy":{"name":"default","coeffDR":1,"pat":0.95,"rnd":0.01},"dice":[{"x":0,"y":0,"col":1,"fS":23,"cS":19},{"x":1,"y":1,"col":1,"fS":9,"cS":9},{"x":2,"y":2,"col":1,"fS":17,"cS":25},{"x":3,"y":0,"col":1,"fS":22,"cS":22},{"x":6,"y":1,"col":1,"fS":24,"cS":24},{"x":6,"y":4,"col":1,"fS":14,"cS":19},{"x":6,"y":0,"col":1,"fS":9,"cS":5},{"x":7,"y":1,"col":1,"fS":9,"cS":9},{"x":8,"y":0,"col":1,"fS":19,"cS":19},{"x":0,"y":8,"col":-1,"fS":17,"cS":17},{"x":1,"y":8,"col":-1,"fS":17,"cS":3},{"x":2,"y":8,"col":-1,"fS":19,"cS":7},{"x":3,"y":4,"col":-1,"fS":18,"cS":23},{"x":4,"y":8,"col":-1,"fS":24,"cS":24},{"x":5,"y":8,"col":-1,"fS":8,"cS":23},{"x":5,"y":7,"col":-1,"fS":10,"cS":21},{"x":7,"y":8,"col":-1,"fS":3,"cS":3},{"x":2,"y":2,"col":-1,"fS":0,"cS":7}],"history":{"moves":[{"idx":5,"rel":{"dx":-1,"dy":0,"fX":1}},{"idx":12,"rel":{"dx":-1,"dy":1,"fX":1}},{"idx":4,"rel":{"dx":1,"dy":0,"fX":1}},{"idx":15,"rel":{"dx":-1,"dy":-1,"fX":0}},{"idx":4,"rel":{"dx":1,"dy":0,"fX":1}},{"idx":12,"rel":{"dx":1,"dy":-5,"fX":0}},{"idx":5,"rel":{"dx":2,"dy":4,"fX":0}},{"idx":17,"rel":{"dx":-2,"dy":-1,"fX":1}},{"idx":4,"rel":{"dx":0,"dy":1,"fX":0}},{"idx":17,"rel":{"dx":2,"dy":-3,"fX":1}},{"idx":1,"rel":{"dx":0,"dy":1,"fX":0}},{"idx":17,"rel":{"dx":-2,"dy":-1,"fX":0}},{"idx":7,"rel":{"dx":0,"dy":1,"fX":0}},{"idx":17,"rel":{"dx":-4,"dy":-1,"fX":0}},{"idx":2,"rel":{"dx":0,"dy":2,"fX":0}}],"deaths":[-1,-1,-1,-1,-1,-1,-1,2,-1,-1,-1,-1,-1,-1,-1],"movesPending":[],"deathsPending":[]}}

**Comment by lettis** [comment]
my build (current version) does not crash.
guessing from the error message, it's the old crash due to uninitialized X11 thread support.
try to pull updates, make clean (or better delete build dir) and rebuild complete project.
